### ISSUE TITLE
open it with different mods folder

### ISSUE THREAD

**Issue by sl5net** [0ad-matters/0ad-appimage#22]
i try open with using a different folder for mods
it use  ~/.local/share/0ad/mods/

I have tried

~/Applications/0ad-0.0.26-alpha-2210110407-x86_64_0...81.AppImage ~/.local/share/0ad/mods2/

and got: 

Skipping file '~/.local/share/0ad/mods2/' which does not have a mod file extension.

reason/discussion: https://wildfiregames.com/forum/topic/107384-change-mods_path

**Comment by StanleySweet** [comment]
That's not how it works. You're telling it to install a mod, not open a mod folder.

**Comment by andy5995** [comment]
I answered at https://wildfiregames.com/forum/topic/107384-change-mods_path/?do=findComment&comment=552099

>You might find this to be a satisfying solution:

`HOME=$HOME/0adA27 ./0ad-0.0.27-rc1-27645-alpha-2305191528-x86_64.AppImage`

>Then you'll probably want to copy your existing config into the ~/0adA27/.config folder
